language: python

sudo: required
os: linux
dist: trusty
group: edge

services:
    - docker
python:
    - "3.6"

env:
    matrix:
        - TESTENV=tests

before_install:
  - wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bigWigToWig
  - chmod +x ./bigWigToWig
# command to install dependencies
install:
    - if [[ "$TESTENV" == "tests" ]]; then pip3 install cwlref-runner;fi

# command to run tests
script:
    - if [[ "$TESTENV" == "tests" ]]; then pytest tests; fi
